[tool.ruff]
line-length = 120
target-version = "py311"
lint.select = ["E", "F", "I", "UP"]
lint.ignore = ["D203"]

[tool.pytest.ini_options]
addopts = "-ra --cov"
testpaths = ["tests"]
pythonpath = ['.']

[tool.coverage.report]
show_missing = true

